#ifndef LV_SETTINGS_PALETTE_H
#define LV_SETTINGS_PALETTE_H
/* Settings actions and PIN keys share these semantic color tokens. */
#define LV_SETTINGS_CONTROL_SURFACE 0xF7F7F7
#define LV_SETTINGS_CONTROL_PRESSED 0xE2E9EE
#define LV_SETTINGS_ACTION_DIVIDER 0xB8C4CC
#define LV_SETTINGS_ROW_DIVIDER 0xD6DEE3
#define LV_SETTINGS_PRIMARY 0x1559B7
#define LV_SETTINGS_PRIMARY_PRESSED 0x10488F
#define LV_SETTINGS_DESTRUCTIVE 0xB42332
#define LV_SETTINGS_DESTRUCTIVE_PRESSED 0x8F1C28
#define LV_SETTINGS_ACTION_TEXT 0x25343F
#define LV_SETTINGS_DISABLED_SURFACE 0xE8EBEE
#define LV_SETTINGS_DISABLED_TEXT 0x64717C
#endif
