/* Generated by gen_currency_view_atlas.py; do not edit. */
#ifndef UN260_CURR_VIEW_ATLAS_H
#define UN260_CURR_VIEW_ATLAS_H
#define CURR_VIEW_ATLAS_PATH "L:/usr/local/share/lvgl_data/currency_view/flags.png"
#define CURR_VIEW_ATLAS_WIDTH 768
#define CURR_VIEW_ATLAS_HEIGHT 324
#define CURR_VIEW_ATLAS_TILE_WIDTH 96
#define CURR_VIEW_ATLAS_TILE_HEIGHT 54
static const struct { const char *file; int x, y; } curr_view_atlas_entries[] = {
    {"CURR_AED.png", 0, 0},
    {"CURR_AMD.png", 96, 0},
    {"CURR_AUD.png", 192, 0},
    {"CURR_AUTO.png", 288, 0},
    {"CURR_AZN.png", 384, 0},
    {"CURR_CAD.png", 480, 0},
    {"CURR_CHF.png", 576, 0},
    {"CURR_CNY.png", 672, 0},
    {"CURR_DZD.png", 0, 54},
    {"CURR_EGP.png", 96, 54},
    {"CURR_EUR.png", 192, 54},
    {"CURR_GBP.png", 288, 54},
    {"CURR_HKD.png", 384, 54},
    {"CURR_IDR.png", 480, 54},
    {"CURR_ILS.png", 576, 54},
    {"CURR_INR.png", 672, 54},
    {"CURR_IQD.png", 0, 108},
    {"CURR_IRR.png", 96, 108},
    {"CURR_ISK.png", 192, 108},
    {"CURR_JPY.png", 288, 108},
    {"CURR_KRW.png", 384, 108},
    {"CURR_LBP.png", 480, 108},
    {"CURR_MAD.png", 576, 108},
    {"CURR_MOP.png", 672, 108},
    {"CURR_MUR.png", 0, 162},
    {"CURR_MXN.png", 96, 162},
    {"CURR_OMR.png", 192, 162},
    {"CURR_PHP.png", 288, 162},
    {"CURR_PKR.png", 384, 162},
    {"CURR_PLN.png", 480, 162},
    {"CURR_QAR.png", 576, 162},
    {"CURR_RUB.png", 672, 162},
    {"CURR_SAR.png", 0, 216},
    {"CURR_SGD.png", 96, 216},
    {"CURR_SOS.png", 192, 216},
    {"CURR_THB.png", 288, 216},
    {"CURR_TJS.png", 384, 216},
    {"CURR_TRY.png", 480, 216},
    {"CURR_UAH.png", 576, 216},
    {"CURR_USD.png", 672, 216},
    {"CURR_XAF.png", 0, 270},
    {"CURR_XOF.png", 96, 270},
    {"CURR_ZAR.png", 192, 270},
    {"multi_card.png", 288, 270},
};
#endif
