#!/usr/bin/env python3
"""Read-only qualification of the three UPKs and their installed target files."""
import argparse
import hashlib
import json
from pathlib import Path
from build_delta import load
from build_storage_bootstrap import APPROVED, PATHS


def verify(images, target, migration):
    internal = images / 'un260_internal'
    packages_dir = internal if internal.is_dir() else images
    packages = {'normal': packages_dir / 'UN260_APPLICATION.upk',
                'bootstrap': packages_dir / 'UN260_STORAGE_BOOTSTRAP.upk', 'migration': migration}
    loaded = {k: load(v) for k, v in packages.items()}
    full_meta, full = loaded['normal']
    assert full_meta['storage_layout'] == 'app-volume-v1'
    assert full_meta['storage_guard'] == 'syncfs-v1'
    assert full['usr/local/bin/un260_storage_sync'][0].startswith(b'\x7fELF')
    mismatches = []
    for name, (data, mode) in full.items():
        f = target / name
        if not f.is_file() or f.read_bytes() != data or (f.stat().st_mode & 0o777) != mode:
            mismatches.append(name)
    # package-version is generated by the release builder, not runtime user data.
    mismatches = [p for p in mismatches if p != 'etc/un260/package-version']
    assert not mismatches, mismatches
    for flavor in ('bootstrap', 'migration'):
        meta, files = loaded[flavor]
        assert set(files) == set(PATHS)
        assert files == {p: full[p] for p in PATHS}
        assert meta['storage_layout'] == 'app-volume-v1'
        assert meta['storage_guard'] == 'syncfs-v1'
        assert ('usr/local/bin/test_lvgl' not in files and 'etc/un260/package-version' not in files)
    assert 'storage_migration' not in full_meta
    assert 'storage_migration' not in loaded['bootstrap'][0]
    assert loaded['migration'][0]['storage_migration'] == APPROVED
    assert loaded['migration'][0]['package_type'] == 'storage-migration'
    helper = full['usr/local/bin/un260_app_storage'][0].decode()
    assert 'APPROVED=' + APPROVED in helper
    assert 'UN260_MTD_STREAM_1' in helper and 'verify_current_nand' in helper
    assert b'UN260_STORAGE_STREAM_1' in full['usr/local/bin/un260_storage_sync'][0]
    required = sum((len(full[p][0]) + 1023) // 1024 + 4 for p in PATHS) + 2048
    assert required <= 2304
    startup = full['etc/init.d/S00lvgl'][0].decode()
    assert startup.index('un260_app_storage --prepare') < startup.index('ui_update.sh --recover')
    assert startup.index('ui_update.sh --recover') < startup.index('"$DAEMON" $DAEMONOPTS')
    return dict(verification='PASS', board_validated=False, bootstrap_root_required_kb=required,
        app_bytes=len(full['usr/local/bin/test_lvgl'][0]), app_sha256=hashlib.sha256(full['usr/local/bin/test_lvgl'][0]).hexdigest(),
        lib_sha256=hashlib.sha256(full['usr/local/lib/liblvgl.so'][0]).hexdigest(),
        full_payload_files=len(full), full_payload_bytes=sum(len(v[0]) for v in full.values()),
        packages={k: dict(bytes=p.stat().st_size, sha256=hashlib.sha256(p.read_bytes()).hexdigest(),
                          version=loaded[k][0]['version']) for k, p in packages.items()})


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--images', type=Path, required=True)
    parser.add_argument('--target', type=Path, required=True)
    parser.add_argument('--migration', type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(verify(args.images, args.target, args.migration), indent=2))
