#!/usr/bin/env python3
"""Deterministic PNG/JPEG/BMP -> BGRA8888 C assets for the UN260 GE decoder.
Run from any directory. Original images are never changed or deleted.
Pillow is a HOST dependency (python3-pil). --check verifies without writing.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
from PIL import Image

MARK = '/* Generated by convert_lvgl_assets.py; DO NOT EDIT. */\n'
VERSION = 2
# Keep flash-friendly compressed backgrounds/cards external. Never allow a
# resource import to silently turn the executable into a framebuffer archive.
MAX_ICON_SIDE = 64
MAX_EMBEDDED_BYTES = 256 * 1024
ROOT = Path(__file__).resolve().parents[1]

def sha(data):
    return hashlib.sha256(data).hexdigest()

def save(path, text, check):
    data = text.encode('utf-8')
    if path.exists() and path.read_bytes() == data:
        return
    if check:
        raise RuntimeError('outdated generated asset: ' + str(path))
    if path.is_symlink():
        raise RuntimeError('refuse generated symlink: ' + str(path))
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + '.tmp')
    tmp.write_bytes(data)
    os.replace(tmp, path)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    source = ROOT / 'aic_ui/lvgl_data'
    dest = ROOT / 'aic_ui/generated_assets'
    old_path = dest / 'manifest.json'
    old = json.loads(old_path.read_text()) if old_path.exists() else {}
    entries, files, external = [], [], []
    embedded_bytes = 0
    for path in sorted(source.rglob('*'), key=lambda p: p.relative_to(source).as_posix()):
        if path.suffix.lower() not in ('.png', '.jpg', '.jpeg', '.bmp') or not path.is_file():
            continue
        if path.is_symlink():
            raise RuntimeError('source image symlink needs explicit review: ' + str(path))
        rel = path.relative_to(source).as_posix()
        if any(c in rel for c in (';', '$', '"', '\\', '\n', '\r')):
            raise RuntimeError('unsupported build metacharacter in image filename: ' + rel)
        raw_input = path.read_bytes()
        with Image.open(path) as im:
            if getattr(im, 'n_frames', 1) != 1:
                raise RuntimeError('animated input is not a static image: ' + rel)
            width, height = im.size
        size = width * height * 4
        if (width > MAX_ICON_SIDE or height > MAX_ICON_SIDE or
                embedded_bytes + size > MAX_EMBEDDED_BYTES):
            if path.suffix not in ('.png', '.jpg', '.jpeg'):
                raise RuntimeError('external decoder requires lowercase .png/.jpg/.jpeg; '
                                   'convert this oversized/budget-excluded image to PNG: ' + rel)
            external.append(dict(name=rel, width=width, height=height,
                                 source_sha256=sha(raw_input),
                                 reason='dimensions' if max(width, height) > MAX_ICON_SIDE else 'budget'))
            continue
        embedded_bytes += size
        name = 'un260_asset_' + sha(rel.encode())[:16]
        target = rel + '.c'
        previous = next((e for e in old.get('entries', []) if e['name'] == rel), None)
        if (old.get('version') == VERSION and previous and previous['source_sha256'] == sha(raw_input)
                and (dest / target).is_file() and sha((dest / target).read_bytes()) == previous['c_sha256']):
            entries.append(previous)
            files.append(target)
            continue
        with Image.open(path) as im:
            if getattr(im, 'n_frames', 1) != 1:
                raise RuntimeError('animated input is not a static image: ' + rel)
            rgba = im.convert('RGBA')
            width, height = rgba.size
            if not (0 < width <= 2047 and 0 < height <= 2047):
                raise RuntimeError('LVGL v8 image dimension limit: ' + rel)
            alpha = rgba.getchannel('A').getextrema()[0] != 255
            pixels = (rgba.tobytes('raw', 'BGRA') if alpha else
                      rgba.convert('RGB').tobytes('raw', 'BGR'))
            stride = width * (4 if alpha else 3)
        lines = [MARK, '#include "aic_ui/compiled_asset.h"\n',
                 'static const unsigned char pixels[] __attribute__((aligned(16))) =\n']
        for i in range(0, len(pixels), 64):
            lines.append('"' + ''.join('\\x%02x' % b for b in pixels[i:i+64]) + '"\n')
        lines += [';\n', 'const un260_compiled_asset_t %s = {%s, %d, %d, %d, %d, pixels};\n' %
                  (name, json.dumps(rel), width, height, stride, int(alpha))]
        text = ''.join(lines)
        save(dest / target, text, args.check)
        entries.append(dict(name=rel, symbol=name, c_file=target, width=width, height=height,
                            stride=stride, bytes=len(pixels), alpha=alpha,
                            format='ARGB8888_LE_BGRA' if alpha else 'RGB888_LE_BGR',
                            source_sha256=sha(raw_input), pixel_sha256=sha(pixels), c_sha256=sha(text.encode())))
        files.append(target)
    index = MARK + '#include "aic_ui/compiled_asset.h"\n#include <string.h>\n'
    for e in entries:
        index += 'extern const un260_compiled_asset_t %s;\n' % e['symbol']
    index += 'static const un260_compiled_asset_t *const assets[] = {\n'
    index += (''.join('    &%s,\n' % e['symbol'] for e in entries) or '    NULL,\n') + '};\n'
    index += '#define ASSET_COUNT %du\n' % len(entries)
    index += '''const un260_compiled_asset_t *un260_compiled_asset_find(const char *path)
{
    const char prefix[] = "/usr/local/share/lvgl_data/";
    if (!path) return NULL;
    if (path[0] == 'L' && path[1] == ':') path += 2;
    if (strncmp(path, prefix, sizeof(prefix)-1)) return NULL;
    path += sizeof(prefix)-1;
    size_t lo = 0, hi = ASSET_COUNT;
    while (lo < hi) {
        size_t mid = lo + (hi-lo)/2;
        int c = strcmp(path, assets[mid]->name);
        if (!c) return assets[mid];
        if (c < 0) hi = mid; else lo = mid+1;
    }
    return NULL;
}
'''
    index += 'unsigned un260_compiled_asset_count(void) { return %d; }\n' % len(entries)
    index += 'unsigned un260_compiled_asset_bytes(void) { return %d; }\n' % sum(e['bytes'] for e in entries)
    save(dest / 'asset_registry.c', index, args.check)
    cmake = '# Generated by convert_lvgl_assets.py\nset(UN260_ASSET_SOURCES\n'
    cmake += ''.join('    "${CMAKE_CURRENT_SOURCE_DIR}/aic_ui/generated_assets/%s"\n' % f for f in files)
    cmake += '    "${CMAKE_CURRENT_SOURCE_DIR}/aic_ui/generated_assets/asset_registry.c"\n)\n'
    save(dest / 'assets.cmake', cmake, args.check)
    for e in old.get('entries', []):
        if e['c_file'] not in files:
            stale = (dest / e['c_file']).resolve()
            if dest.resolve() not in stale.parents or not stale.is_file():
                continue
            if args.check:
                raise RuntimeError('stale generated file: ' + str(stale))
            if stale.open().read(len(MARK)) == MARK:
                stale.unlink()  # Only previously manifested generated files.
    manifest = dict(version=VERSION, entries=entries, external=external,
                    max_icon_side=MAX_ICON_SIDE, max_embedded_bytes=MAX_EMBEDDED_BYTES,
                    total_raw_bytes=sum(e['bytes'] for e in entries))
    save(old_path, json.dumps(manifest, indent=2, ensure_ascii=False) + '\n', args.check)
    print('UN260 assets: %d images, %d raw bytes, %s' % (len(entries), manifest['total_raw_bytes'], dest))
    print('UN260 assets: %d compressed external images (original paths and decoder cache retained)' % len(external))

if __name__ == '__main__':
    main()
