#!/usr/bin/env python3
"""Reproduce the original Currency star bitmaps (offline, Pillow required)."""
import math
from pathlib import Path
from PIL import Image, ImageDraw

root = Path(__file__).resolve().parents[1]
target = root / 'un260/lv_core/page_07_curr/page_07_curr_star.h'
lines = ['/* Generated by tools/gen_curr_star.py; original project artwork. */',
         '#ifndef PAGE07_CURR_STAR_H', '#define PAGE07_CURR_STAR_H']
for name, rgb in [('outline', (160, 173, 183)), ('filled', (55, 125, 174))]:
    scale = 8
    im = Image.new('L', (24*scale, 24*scale))
    draw = ImageDraw.Draw(im)
    points = []
    for i in range(10):
        angle = -math.pi/2 + i*math.pi/5
        radius = 9 if i%2 == 0 else 4.4
        points.append(((12+radius*math.cos(angle))*scale,
                       (12+radius*math.sin(angle))*scale))
    if name == 'filled': draw.polygon(points, fill=255)
    draw.line(points+[points[0]], fill=255, width=12, joint='curve')
    for x, y in points: draw.ellipse((x-6,y-6,x+6,y+6), fill=255)
    im = im.resize((24,24), getattr(Image, 'Resampling', Image).LANCZOS)
    palette = b''.join(bytes((rgb[2],rgb[1],rgb[0],alpha)) for alpha in range(256))
    data = palette + im.tobytes()
    symbol = 'curr_star_'+name
    lines += ['static const uint8_t '+symbol+'_pixels[] = {',
              '\n'.join(','.join(str(b) for b in data[i:i+24])+',' for i in range(0,len(data),24)),
              '};', 'static const lv_img_dsc_t '+symbol+' = {',
              ' .header={.cf=LV_IMG_CF_INDEXED_8BIT,.w=24,.h=24},',
              ' .data_size=sizeof('+symbol+'_pixels),.data='+symbol+'_pixels', '};']
lines += ['#endif', '']
target.write_text('\n'.join(lines))
