#!/usr/bin/env python3
"""Offline shaping: a whole handwritten word is one 4bpp LVGL glyph.

No runtime font shaping, stroke tessellation, or image decoding is needed.
The native renderer reads this same committed bitmap, so handoff is exact.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

root = Path(__file__).resolve().parents[1]
font = ImageFont.truetype(str(root / 'aic_ui/font/OoohBaby-Regular.ttf'), 560)
if not hasattr(font, 'getbbox') or not hasattr(Image, 'Resampling'):
    raise SystemExit('Regeneration needs Pillow >= 10 on the host; normal firmware builds use the committed C glyph.')
box = font.getbbox('Welcome', stroke_width=4)
mask = Image.new('L', (box[2]-box[0]+16, box[3]-box[1]+16))
ImageDraw.Draw(mask).text((8-box[0], 8-box[1]), 'Welcome', font=font,
                          fill=255, stroke_width=4)
mask.thumbnail((480, 112), Image.Resampling.LANCZOS)
w, h = mask.size
alpha = [(v+8)//17 for v in mask.tobytes()]
if len(alpha) % 2:
    alpha.append(0)
data = bytes((alpha[i] << 4) | alpha[i+1] for i in range(0, len(alpha), 2))
bitmap = '\n'.join('    ' + ','.join(f'0x{v:02x}' for v in data[i:i+24]) + ','
                   for i in range(0, len(data), 24))
text = '''/* Generated by tools/gen_boot_welcome.py. Oooh Baby: SIL OFL 1.1.
 * U+E000 is the complete, pre-shaped Welcome word, not a general font. */
#include "lvgl/lvgl.h"
static const uint8_t glyph_bitmap[] = {
%s
};
static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 0, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = 0, .ofs_y = 0}
};
static const lv_font_fmt_txt_cmap_t cmaps[] = {{
    .range_start = 57344, .range_length = 1, .glyph_id_start = 1,
    .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,
    .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
}};
static lv_font_fmt_txt_glyph_cache_t cache;
static lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap, .glyph_dsc = glyph_dsc, .cmaps = cmaps,
    .kern_dsc = NULL, .kern_scale = 0, .cmap_num = 1, .bpp = 4,
    .kern_classes = 0, .bitmap_format = 0, .cache = &cache
};
const lv_font_t lv_font_boot_welcome = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = %d, .base_line = 0, .dsc = &font_dsc
};
''' % (bitmap, w*16, w, h, h)
(root / 'un260/font/lv_font_boot_welcome.c').write_text(text)
print(f'Welcome: {w}x{h}, {len(data)} bytes; one pre-shaped glyph')
