#!/usr/bin/env python3
"""Import the updater's public status messages without changing its wire format.

Use --script ROOT/target/d211/d213_devkitf/rootfs_overlay/usr/bin/ui_update.sh
after changing updater messages. --check also checks that source when present.
Unknown future/external diagnostics remain literal; never treat them as printf.
"""
from pathlib import Path
import argparse
import json
import re
import shlex

ROOT = Path(__file__).resolve().parents[1]
RELATIVE = 'target/d211/d213_devkitf/rootfs_overlay/usr/bin/ui_update.sh'
RECORD = ROOT / 'i18n/external/updater.json'
FRAGMENT = ROOT / 'i18n/fragments/updater.en.json'
TABLE = ROOT / 'un260/lv_system/ui_update_templates.inc'
QUOTED = r'''(?:"[^"\n]*"|'[^'\n]*')'''
VARIABLE = re.compile(r'\$\{[A-Za-z_][A-Za-z_0-9]*\}|\$[A-Za-z_][A-Za-z_0-9]*')


def extract(source):
    messages = set()
    for line in source.splitlines():
        if line.lstrip().startswith('#'):
            continue
        for match in re.finditer(r'\b(?:fail_update|finish_success)\s+(' + QUOTED + ')', line):
            messages.add(shlex.split(match[1])[0])
        match = re.search(r'\bcompletion_message=(' + QUOTED + ')', line)
        if match:
            messages.add(shlex.split(match[1])[0])
        if 'write_status ' in line:
            args = shlex.split(line.split('write_status ', 1)[1])
            if len(args) >= 5 and args[4] and not args[4].startswith('$'):
                messages.add(args[4])
    return sorted(text for text in messages if not text.startswith('$'))


def outputs(messages):
    catalog, rows = {}, []
    for source in messages:
        parts = VARIABLE.split(source)
        key = '%s'.join(part.replace('%', '%%') for part in parts)
        catalog[key] = key
        if len(parts) > 1:
            if len(parts) > 3 or any('$' in part for part in parts):
                raise ValueError('Unsupported public status template: ' + source)
            fields = [str(len(parts)-1), 'UI_N_(' + json.dumps(key) + ')']
            fields += [json.dumps(part) for part in (parts if len(parts) == 3 else [parts[0], '', parts[1]])]
            rows.append('    {' + ', '.join(fields) + '},')
    return {FRAGMENT: json.dumps({'en': catalog}, ensure_ascii=False, indent=2)+'\n',
            TABLE: '/* Generated by tools/gen_update_messages.py. */\n' + '\n'.join(rows)+'\n'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--script', type=Path)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if args.script and not args.check:
        messages = extract(args.script.read_text(encoding='utf-8'))
        RECORD.parent.mkdir(parents=True, exist_ok=True)
        RECORD.write_bytes((json.dumps({'source': RELATIVE, 'messages': messages}, indent=2)+'\n').encode())
    else:
        messages = json.loads(RECORD.read_text(encoding='utf-8'))['messages']
    if args.check:
        source = args.script or ROOT.parents[2] / RELATIVE
        if source.exists() and extract(source.read_text(encoding='utf-8')) != messages:
            raise SystemExit('Updater display messages changed; reimport with --script, then regenerate i18n')
    for path, text in outputs(messages).items():
        if args.check:
            if not path.exists() or path.read_bytes() != text.encode('utf-8'):
                raise SystemExit('Stale updater text output: ' + str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(text.encode('utf-8'))
    print(f'Updater display text: {len(messages)} messages checked')


if __name__ == '__main__':
    main()
