#!/usr/bin/env python3
"""Original geometric status artwork; offline 8x coverage, no symbol fonts.

Emit LVGL indexed bitmaps so every color depth uses the same palette/alpha.
PNG previews are review assets, not runtime dependencies.
"""
from pathlib import Path
from PIL import Image, ImageDraw
root = Path(__file__).resolve().parents[1]
out = root / 'aic_ui/generated_assets'
out.mkdir(parents=True, exist_ok=True)
lines = ['/* Generated by tools/gen_selfcheck_icons.py; original project artwork. */',
         '#ifndef UN260_SELFCHECK_ICONS_H', '#define UN260_SELFCHECK_ICONS_H']
scale = 8
for name, color in [('pass', '#2C9C7C'), ('fail', '#BD3323')]:
    im = Image.new('RGBA', (18*scale, 18*scale))
    d = ImageDraw.Draw(im)
    def circle(x, y, r, fill):
        d.ellipse(((x-r)*scale, (y-r)*scale, (x+r)*scale, (y+r)*scale), fill=fill)
    circle(9, 9, 8.6, color)
    if name == 'pass':
        points = [(4.4, 9), (7.5, 12), (13.4, 6)]
        d.line([(x*scale,y*scale) for x,y in points], fill='white', width=round(1.65*scale), joint='curve')
        for x,y in points: circle(x,y,.825,'white')
    else:
        d.rectangle((8.2*scale,5*scale,9.8*scale,9.6*scale), fill='white')
        circle(9,5,.8,'white')
        circle(9,9.6,.8,'white')
        circle(9,13,.9,'white')
    im = im.resize((18,18), getattr(Image, 'Resampling', Image).LANCZOS)
    im.save(out / ('selfcheck_'+name+'.png'))
    # At most 256 exact RGBA colors, transparent palette entries padded to 256.
    colors = list(dict.fromkeys(im.getdata()))
    assert len(colors) <= 256
    palette = b''.join(bytes((c[2],c[1],c[0],c[3])) for c in colors) + bytes((256-len(colors))*4)
    indices = bytes(colors.index(c) for c in im.getdata())
    data = palette + indices
    symbol = 'selfcheck_'+name
    lines += ['static const uint8_t '+symbol+'_pixels[] = {',
              '\n'.join(','.join(str(b) for b in data[i:i+24])+',' for i in range(0,len(data),24)), '};',
              'static const lv_img_dsc_t '+symbol+' = {',
              ' .header = {.cf=LV_IMG_CF_INDEXED_8BIT,.w=18,.h=18},',
              ' .data_size=sizeof('+symbol+'_pixels),.data='+symbol+'_pixels', '};']
lines += ['#endif', '']
text = '\n'.join(lines)
target = out / 'selfcheck_icons.h'
if not target.exists() or target.read_text() != text: target.write_text(text)
