#!/usr/bin/env python3
"""Pack the existing currency artwork at VIEW size. Originals stay untouched.

One external PNG, one decoder-cache slot, no runtime resizing. The resource
map is generated from filenames, not from a hard-coded controller catalog.
"""
from pathlib import Path
from io import BytesIO
import argparse
import hashlib
import json
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
WIDTH, HEIGHT, COLUMNS = 96, 54, 8


def save(path, data, check):
    if path.exists() and path.read_bytes() == data:
        return
    if check:
        raise RuntimeError(f"Stale Currency VIEW asset: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = ROOT / 'aic_ui/lvgl_data'
    sources = sorted(data.glob('CURR_*.png')) + [data / 'main_icons/multi_card.png']
    assert sources and len(sources) <= 64, 'Review atlas memory budget for a larger artwork catalog'
    atlas = Image.new('RGBA', (COLUMNS * WIDTH, ((len(sources)+COLUMNS-1)//COLUMNS)*HEIGHT))
    entries = []
    for i, path in enumerate(sources):
        with Image.open(path) as source:
            flag = source.convert('RGBA')
            flag.thumbnail((WIDTH, HEIGHT), getattr(Image, 'Resampling', Image).LANCZOS)
        x, y = (i % COLUMNS)*WIDTH, (i // COLUMNS)*HEIGHT
        atlas.paste(flag, (x+(WIDTH-flag.width)//2, y+(HEIGHT-flag.height)//2))
        entries.append(dict(name=path.name, x=x, y=y,
                            sha256=hashlib.sha256(path.read_bytes()).hexdigest()))
    png = BytesIO()
    atlas.save(png, format='PNG', optimize=True)
    save(data / 'currency_view/flags.png', png.getvalue(), args.check)
    header = ['/* Generated by gen_currency_view_atlas.py; do not edit. */',
              '#ifndef UN260_CURR_VIEW_ATLAS_H', '#define UN260_CURR_VIEW_ATLAS_H',
              '#define CURR_VIEW_ATLAS_PATH "L:/usr/local/share/lvgl_data/currency_view/flags.png"',
              f'#define CURR_VIEW_ATLAS_WIDTH {atlas.width}',
              f'#define CURR_VIEW_ATLAS_HEIGHT {atlas.height}',
              f'#define CURR_VIEW_ATLAS_TILE_WIDTH {WIDTH}',
              f'#define CURR_VIEW_ATLAS_TILE_HEIGHT {HEIGHT}',
              'static const struct { const char *file; int x, y; } curr_view_atlas_entries[] = {']
    header += [f'    {{"{e["name"]}", {e["x"]}, {e["y"]}}},' for e in entries]
    header += ['};', '#endif', '']
    save(ROOT / 'un260/lv_resources/lv_curr/curr_view_atlas.h', '\n'.join(header).encode(), args.check)
    save(data / 'currency_view/manifest.json', (json.dumps(dict(width=atlas.width, height=atlas.height,
         tile_width=WIDTH, tile_height=HEIGHT, entries=entries), indent=2)+'\n').encode(), args.check)
    print(f'Currency VIEW: {len(entries)} flags in {atlas.width}x{atlas.height} atlas; {atlas.width*atlas.height*4} decoded bytes')


if __name__ == '__main__':
    main()
