#!/usr/bin/env python3
"""Compile the approved, cropped guide layers into immutable BGRA LVGL images.
No image decoding, scaling, filesystem I/O or allocation occurs per animation frame.
The PNG sources and standalone SVG masters live in tools/icon_sources/fault_guide.
"""
import argparse
import hashlib
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / 'tools/icon_sources/fault_guide'
OUT = ROOT / 'aic_ui/generated_fault_guide'
HEADER = ROOT / 'un260/lv_components/fault_guide/machine_fault_assets.h'

def generate(check=False):
    meta = json.loads((SRC / 'manifest.json').read_text(encoding='utf-8'))
    header = '''#ifndef UN260_MACHINE_FAULT_ASSETS_H
#define UN260_MACHINE_FAULT_ASSETS_H
#include "lvgl/lvgl.h"
typedef struct { const lv_img_dsc_t *image; int16_t x, y; } machine_fault_asset_t;
extern const machine_fault_asset_t mf_asset_front, mf_asset_side, mf_asset_top, mf_asset_rear;
extern const machine_fault_asset_t mf_asset_lid[12], mf_asset_rear_tray, mf_asset_rear_face;
#endif
'''
    chunks = ['/* Generated by tools/gen_machine_fault_assets.py. Do not edit. */\n#include "un260/lv_components/fault_guide/machine_fault_assets.h"\n#if LV_COLOR_DEPTH != 32\n#error "Machine guide BGRA assets require the production 32-bit color format"\n#endif\n']
    entries = []
    total = 0
    for name in meta['assets']:
        image = Image.open(SRC / (name + '.png')).convert('RGBA')
        box = image.getchannel('A').getbbox()
        if not box:
            raise RuntimeError('Empty asset: ' + name)
        image = image.crop(box)
        data = image.tobytes('raw', 'BGRA')
        total += len(data)
        w, h = image.size
        chunks.append('static const uint8_t data_' + name + '[] = {\n')
        chunks.extend('    ' + ','.join('0x%02x' % b for b in data[i:i+24]) + ',\n' for i in range(0, len(data), 24))
        chunks.append('};\nstatic const lv_img_dsc_t image_%s = {.header={.cf=LV_IMG_CF_TRUE_COLOR_ALPHA,.w=%d,.h=%d},.data_size=sizeof(data_%s),.data=data_%s};\n' % (name,w,h,name,name))
        entries.append({'name':name,'x':box[0],'y':box[1],'w':w,'h':h,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()})
    if total > 2 * 1024 * 1024:
        raise RuntimeError('Machine guide exceeded 2 MiB immutable asset budget: ' + str(total))
    for entry in entries:
        if not entry['name'].startswith('lid_'):
            chunks.append('const machine_fault_asset_t mf_asset_%s = {&image_%s,%d,%d};\n' % (entry['name'],entry['name'],entry['x'],entry['y']))
    chunks.append('const machine_fault_asset_t mf_asset_lid[12] = {\n')
    for entry in entries:
        if entry['name'].startswith('lid_'):
            chunks.append('    {&image_%s,%d,%d},\n' % (entry['name'],entry['x'],entry['y']))
    chunks.append('};\n')
    outputs={HEADER:header,OUT/'machine_fault_assets.c':''.join(chunks),SRC/'compiled-manifest.json':json.dumps({'bytes':total,'assets':entries},indent=2)+'\n'}
    for target, text in outputs.items():
        if target.exists() and target.read_text(encoding='utf-8')==text:
            continue
        if check:
            raise RuntimeError('Outdated generated model asset: '+str(target))
        target.parent.mkdir(parents=True,exist_ok=True)
        target.write_bytes(text.encode('utf-8'))
    print('Machine guide: %d layers, %d immutable bytes' % (len(entries), total))

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    generate(parser.parse_args().check)
