#ifndef UN260_BOOT_THEME_CONFIG_H
#define UN260_BOOT_THEME_CONFIG_H
#define UI_BOOT_ANIM_THEME_A 1
#define UI_BOOT_ANIM_THEME_B 2
#define UI_BOOT_ANIM_THEME_C 3
#define UI_BOOT_ANIM_THEME_D 4
#ifndef UI_BOOT_ANIM_THEME
#define UI_BOOT_ANIM_THEME UI_BOOT_ANIM_THEME_D
#endif
#if UI_BOOT_ANIM_THEME < 1 || UI_BOOT_ANIM_THEME > 4
#error "UI_BOOT_ANIM_THEME must be 1, 2, 3 or 4"
#endif
#define UI_BOOT_EARLY_ENABLED (UI_BOOT_ANIM_THEME == 3 || UI_BOOT_ANIM_THEME == 4)
#endif
